version: '3.8'
services:
  primary:
    image: postgres:16rc1-bullseye
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --no-locale
      - TZ=Asia/Tokyo
    ports:
      - 15432:5432
    healthcheck:
      test: pg_isready -U postgres -d postgres
      interval: 1s
      timeout: 1s
      retries: 5
    command:
      - -c
      - config_file=/etc/postgresql/postgresql.conf
      - -c
      - hba_file=/etc/postgresql/pg_hba.conf
    volumes:
      - ./primary/data:/var/lib/postgresql/data
      - ./primary/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./primary/pg_hba.conf:/etc/postgresql/pg_hba.conf
 
