spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    #url: jdbc:postgresql://localhost:15432,localhost:15433,localhost:15434/postgres?loadBalanceHosts=true
    url: jdbc:postgresql://localhost:15432/postgres?autoCommit=false
    username: postgres
    password: postgres
    hikari:
      auto-commit: false
